version: '3'
services:
  dashboard:
    build: .
    volumes:
      - .:/usr/src/app
    command: flask run --host 0.0.0.0
    ports:
    - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - TOKEN=${TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
